name: Create JSON Rules Engine Fork and Upload to Private NPM Registry

on:
  push:
    branches: ['development']

jobs:
  build-and-push-node-tools-dev:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Cache Dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - name: NPM Install and Publish
        run: |
          npm i
          npm publish
          npm run build --if-present
          npm test
        env:
          NODE_AUTH_TOKEN: NPM_TOKEN
